### ISSUE TITLE
[feature] use bn.js instead of bignum

### ISSUE THREAD

**Issue by cesco69** [egnyte/wopi-proof-validator#2]
bignum use node-gyp. [bn.js](https://github.com/indutny/bn.js/) is pure javascript!

migration is simple.

**timeConverter.js**
```js
const BN = require("bn.js");

module.exports = function(timeString) {
    var time = new BN(timeString);
    var approximateTimestamp = time
        .div(new BN('10000'))
        .sub(new BN('62135596800000'))
        .toNumber();
    return approximateTimestamp;
}
```

**payloadBuilder.js**
```js
const BN = require("bn.js");

module.exports = {
    build: function(input) {
        const fullUrl = percentEncode(input.url).toUpperCase(); //not sure about the escaping yet.

        const fullUrlBuffer = Buffer.from(fullUrl, "utf8");
        const accessTokenBuffer = Buffer.from(input.accessToken, "utf8");

        const timeBuffer = new BN(input.timestamp).toBuffer('big', 8); // <-------

        const expectedProofBuffer = Buffer.concat([
            getLengthIn4Bytes(accessTokenBuffer),
            accessTokenBuffer,
            getLengthIn4Bytes(fullUrlBuffer),
            fullUrlBuffer,
            getLengthIn4Bytes(timeBuffer),
            timeBuffer
        ]);

        return expectedProofBuffer;
    }
};
```

**Comment by naugtur** [comment]
I was hoping to wait it out and use bugnum from ecmascript instead, once it ships.

Any benefits of bn.js other than sacrificing a little performance for a cleaner build that we should consider?

**Comment by cesco69** [comment]
> Any benefits of bn.js other than sacrificing a little performance for a cleaner build that we should consider?

yes, bignum require node-gyp that also require python. It's a lot of dependencies... but if you are waiting for ecmascript bignum it's ok.

PS. thanks for your work, it save my day

**Comment by naugtur** [comment]
A lot of fun went into figuring out number endians there :)

What's your case against node-gyp? Maybe I should consider rewriting, but not sure how it'd impact performance. Would definitely be more portable.

**Comment by cesco69** [comment]
in my case, i'm behind company firewall without direct access to internet, node-gyp has a lot of problems for install behind proxy, but my problem isn't common, i think it's a wasting of your time rewriting for  just for this reason.

**Comment by naugtur** [comment]
Is it you yourself, installing in dev environment, or your production deployment? You can (and for production - should) run `npm install` elsewhere and copy the node_modules directory. All you need to do is make sure you install on the same operating system flavor. Run a CI job somewhere and return node_modules as artifacts. 

I'll close this now. Feel free to reopen if you have anything new.
